Feat add controller
antondoddo/metabs pull request #6
Opened 2022-03-20 20:52 UTC by antonio-farina

Hi Dam!

I created some tests for the ElementController.

2022-03-20 21:19 UTC, damianopetrungaro requested changes
Hey! 
Well done, just commented some things I've seen :) 

Let me know what you think!

2022-03-20 21:19 UTC, damianopetrungaro commented on src/main/java/com/github/metabs/model/Element.java
> +@org.springframework.data.neo4j.core.schema.Node("Element")
I think we can add this line to the import block :)

2022-03-20 21:19 UTC, damianopetrungaro commented on src/main/java/com/github/metabs/model/dto/SaveElementDto.java
> +public class SaveElementDto {
Why is this inside the model package? I think we should move it inside the service package

2022-03-20 21:19 UTC, damianopetrungaro commented on src/main/java/com/github/metabs/model/dto/SaveElementRequest.java
> +public class SaveElementRequest {
Why is this inside the model package? I think we should move it inside the controller/request package (or similar)

2022-03-20 21:19 UTC, damianopetrungaro commented on src/main/java/com/github/metabs/model/dto/validator/RequestElementValidator.java
> +public class RequestElementValidator implements Validator {
Why is this inside the model package? I think we should move it inside the controller/validator package

2022-03-20 21:19 UTC, damianopetrungaro commented on src/main/java/com/github/metabs/model/vo/converter/LoggerDecoratorConverter.java
> +package com.github.metabs.model.vo.converter;
For the moment we can delete this if you want :)

2022-03-20 21:19 UTC, damianopetrungaro commented on src/main/java/com/github/metabs/service/ElementService.java
> +  ElementRepository elementRepository;
Add visibility

2022-03-20 21:19 UTC, damianopetrungaro commented on src/main/java/com/github/metabs/service/ElementService.java
> +  CollectionRepository collectionRepository;
Add visibility

2022-03-20 21:19 UTC, damianopetrungaro commented on src/main/java/com/github/metabs/service/ElementService.java
> +    com.github.metabs.model.Element element;
We can reuse the import block for this :)

2022-03-20 21:19 UTC, damianopetrungaro commented on src/main/java/com/github/metabs/service/ElementService.java
> +  public Element saveElement(SaveElementDto saveSaveElementDtoRequestDto) {
```suggestion
  public Element saveElement(SaveElementDto dto) {
```

2022-03-20 21:19 UTC, damianopetrungaro commented on src/main/java/com/github/metabs/service/ElementService.java
> +      UUID id2 = UUID.randomUUID();
Can't we create the `id` variable only once before the first if statement and reuse it?

2022-03-20 21:19 UTC, damianopetrungaro commented on src/main/java/com/github/metabs/service/ElementService.java
> +  public com.github.metabs.model.Element saveElementWithParent(
We can reuse the import block for this :)

2022-03-20 21:19 UTC, damianopetrungaro commented on src/main/java/com/github/metabs/service/ElementService.java
> +    com.github.metabs.model.Element element;
We can reuse the import block for this :)

2022-03-20 21:19 UTC, damianopetrungaro commented on src/main/java/com/github/metabs/service/ElementService.java
> +          id2,
Can't we create the id variable only once before the first if statement and reuse it?

2022-03-20 21:19 UTC, damianopetrungaro commented on src/test/java/com/github/metabs/controller/ElementControllerTest.java
> +  public void setup() {
We should consider moving this inside a configuration for the tests, but maybe not in this PR

2022-03-20 21:19 UTC, damianopetrungaro commented on src/test/java/com/github/metabs/controller/ElementControllerTest.java
> +    MvcResult result = mockMvc.perform(request).andReturn();
Let's use the assertions provided by mockMvc

2022-03-20 21:19 UTC, damianopetrungaro commented on src/test/java/com/github/metabs/controller/ElementControllerTest.java
> + @Test public void shouldReturnNonProcessableEntity() throws Exception {
Add a test for a 422

2022-03-20 21:19 UTC, damianopetrungaro commented on src/test/java/com/github/metabs/controller/serialzer/CollectionJsonSerializerTest.java
> +    UUID idParent = UUID.randomUUID();
User the object mother to create collection

2022-03-20 21:19 UTC, damianopetrungaro commented on src/test/java/com/github/metabs/model/dto/SaveSaveElementDtoRequestDtoTest.java
> +public class SaveSaveElementDtoRequestDtoTest {
Change all the names after you moved again the src class

2022-03-20 21:19 UTC, damianopetrungaro commented on src/test/java/com/github/metabs/model/dto/SaveSaveElementDtoRequestTest.java
> +public class SaveSaveElementDtoRequestTest {
Change all the names after you moved again the src class

2022-03-20 21:19 UTC, damianopetrungaro commented on src/test/java/com/github/metabs/model/dto/SaveSaveElementDtoRequestDtoTest.java
> +    saveElementDto.rename(name);
change to get/set for those methods, the rename are amazing for domain objects, but for DTOs I suggest you to keep them more simple

2022-03-20 21:19 UTC, damianopetrungaro commented on src/test/java/com/github/metabs/service/ElementServiceTest.java
> +  //TODO
To add after this PR get merged

2022-03-21 08:16 UTC, antonio-farina commented on src/main/java/com/github/metabs/controller/ElementController.java
> +  ElementService elementService;
Done

2022-03-21 08:16 UTC, antonio-farina commented on src/main/java/com/github/metabs/controller/ElementController.java
> +  RequestElementValidator validator;
Done

2022-03-21 08:17 UTC, antonio-farina commented on src/main/java/com/github/metabs/controller/ElementController.java
> +      return new ResponseEntity<>(trueElement, HttpStatus.OK);
Done

2022-03-21 08:20 UTC, antonio-farina commented on src/main/java/com/github/metabs/controller/ElementController.java
> +    SaveElementDto saveElementDto = validator.getSaveElementDto();
Done

2022-03-21 08:23 UTC, antonio-farina commented on src/main/java/com/github/metabs/controller/ElementController.java
> +    SaveElementDto saveElementDto = validator.getSaveElementDto();
Done

2022-03-21 08:24 UTC, antonio-farina commented on src/main/java/com/github/metabs/controller/ElementController.java
> +}
Done

2022-03-21 08:27 UTC, antonio-farina commented on src/main/java/com/github/metabs/controller/serializer/CollectionJsonSerializer.java
> +    gen.writeStringField(
Done

2022-03-21 08:28 UTC, antonio-farina commented on src/main/java/com/github/metabs/controller/serializer/TabJsonSerializer.java
> +public class TabJsonSerializer extends JsonSerializer<Tab> {
Done

2022-03-21 08:28 UTC, antonio-farina commented on src/main/java/com/github/metabs/model/Element.java
> +@org.springframework.data.neo4j.core.schema.Node("Element")
Done

2022-03-21 08:30 UTC, antonio-farina commented on src/main/java/com/github/metabs/model/dto/SaveElementDto.java
> +public class SaveElementDto {
Done

2022-03-21 08:32 UTC, antonio-farina commented on src/main/java/com/github/metabs/model/dto/SaveElementRequest.java
> +public class SaveElementRequest {
Done

2022-03-21 08:34 UTC, antonio-farina commented on src/main/java/com/github/metabs/model/dto/validator/RequestElementValidator.java
> +public class RequestElementValidator implements Validator {
Done

2022-03-21 08:37 UTC, antonio-farina commented on src/main/java/com/github/metabs/model/vo/converter/LoggerDecoratorConverter.java
> +package com.github.metabs.model.vo.converter;
Done

2022-03-21 08:38 UTC, antonio-farina commented on src/main/java/com/github/metabs/service/ElementService.java
> +  ElementRepository elementRepository;
Done

2022-03-21 08:38 UTC, antonio-farina commented on src/main/java/com/github/metabs/service/ElementService.java
> +  CollectionRepository collectionRepository;
Done

2022-03-21 08:39 UTC, antonio-farina commented on src/main/java/com/github/metabs/service/ElementService.java
> +    com.github.metabs.model.Element element;
Yes we can!

2022-03-21 08:41 UTC, antonio-farina commented on src/main/java/com/github/metabs/service/ElementService.java
> +  public Element saveElement(SaveElementDto saveSaveElementDtoRequestDto) {
Ok

2022-03-21 08:42 UTC, antonio-farina commented on src/main/java/com/github/metabs/service/ElementService.java
> +      UUID id2 = UUID.randomUUID();
Yes we can!

2022-03-21 08:43 UTC, antonio-farina commented on src/main/java/com/github/metabs/service/ElementService.java
> +  public com.github.metabs.model.Element saveElementWithParent(
Yes!

2022-03-21 08:44 UTC, antonio-farina commented on src/main/java/com/github/metabs/service/ElementService.java
> +    com.github.metabs.model.Element element;
Right!

2022-03-21 08:45 UTC, antonio-farina commented on src/main/java/com/github/metabs/service/ElementService.java
> +          id2,
Right!

2022-03-21 08:46 UTC, antonio-farina commented on src/test/java/com/github/metabs/controller/ElementControllerTest.java
> +  public void setup() {
ok we will talk about it

2022-03-21 08:56 UTC, antonio-farina commented on src/test/java/com/github/metabs/controller/serialzer/CollectionJsonSerializerTest.java
> +    UUID idParent = UUID.randomUUID();
Done

2022-03-21 09:10 UTC, antonio-farina commented on src/test/java/com/github/metabs/model/dto/SaveSaveElementDtoRequestDtoTest.java
> +public class SaveSaveElementDtoRequestDtoTest {
Done

2022-03-21 09:10 UTC, antonio-farina commented on src/test/java/com/github/metabs/model/dto/SaveSaveElementDtoRequestTest.java
> +public class SaveSaveElementDtoRequestTest {
Done

2022-03-21 09:14 UTC, antonio-farina commented on src/test/java/com/github/metabs/model/dto/SaveSaveElementDtoRequestDtoTest.java
> +    saveElementDto.rename(name);
Done

2022-03-21 09:15 UTC, antonio-farina commented on src/test/java/com/github/metabs/service/ElementServiceTest.java
> +  //TODO
ok we will do it later

2022-03-21 10:10 UTC, damianopetrungaro requested changes
You forgot a couple of those :D

2022-03-21 10:16 UTC, antonio-farina commented on src/main/java/com/github/metabs/controller/ElementController.java
> +    if (result.hasErrors()) {
ok

2022-03-21 16:36 UTC, antonio-farina commented on src/main/java/com/github/metabs/controller/ElementController.java
> +      Optional<Element> element = elementService.getElementById(id);
Ok

2022-03-21 17:42 UTC, damianopetrungaro approved these changes

2022-03-21 17:46 UTC, antonio-farina commented
feat:add element RESTAPI

2022-03-21 17:47 UTC, merged